package subjects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"permissions/models"
)

/*DeleteSubjectByExternalIDOK OK

swagger:response deleteSubjectByExternalIdOK
*/
type DeleteSubjectByExternalIDOK struct {
}

// NewDeleteSubjectByExternalIDOK creates DeleteSubjectByExternalIDOK with default headers values
func NewDeleteSubjectByExternalIDOK() *DeleteSubjectByExternalIDOK {
	return &DeleteSubjectByExternalIDOK{}
}

// WriteResponse to the client
func (o *DeleteSubjectByExternalIDOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
}

/*DeleteSubjectByExternalIDNotFound Not Found

swagger:response deleteSubjectByExternalIdNotFound
*/
type DeleteSubjectByExternalIDNotFound struct {

	// In: body
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewDeleteSubjectByExternalIDNotFound creates DeleteSubjectByExternalIDNotFound with default headers values
func NewDeleteSubjectByExternalIDNotFound() *DeleteSubjectByExternalIDNotFound {
	return &DeleteSubjectByExternalIDNotFound{}
}

// WithPayload adds the payload to the delete subject by external Id not found response
func (o *DeleteSubjectByExternalIDNotFound) WithPayload(payload *models.ErrorOut) *DeleteSubjectByExternalIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete subject by external Id not found response
func (o *DeleteSubjectByExternalIDNotFound) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteSubjectByExternalIDNotFound) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteSubjectByExternalIDInternalServerError delete subject by external Id internal server error

swagger:response deleteSubjectByExternalIdInternalServerError
*/
type DeleteSubjectByExternalIDInternalServerError struct {

	// In: body
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewDeleteSubjectByExternalIDInternalServerError creates DeleteSubjectByExternalIDInternalServerError with default headers values
func NewDeleteSubjectByExternalIDInternalServerError() *DeleteSubjectByExternalIDInternalServerError {
	return &DeleteSubjectByExternalIDInternalServerError{}
}

// WithPayload adds the payload to the delete subject by external Id internal server error response
func (o *DeleteSubjectByExternalIDInternalServerError) WithPayload(payload *models.ErrorOut) *DeleteSubjectByExternalIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete subject by external Id internal server error response
func (o *DeleteSubjectByExternalIDInternalServerError) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteSubjectByExternalIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
