---
#############################
# enable/disable all services
#############################
- name: enable anon-files service
  sudo: yes
  service: name={{anon_files.service_name}} enabled={{enable_services}}
  tags:
      - enable_services
      - enable_anon-files

- name: enable exim service
  sudo: yes
  service: name={{exim.service_name}} enabled={{enable_services}}
  tags:
      - enable_services
      - enable_exim

- name: enable saved-searches service
  sudo: yes
  service: name={{saved_searches.service_name}} enabled={{enable_services}}
  tags:
      - enable_services
      - enable_saved-searches

- name: enable user-preferences service
  sudo: yes
  service: name={{user_preferences.service_name}} enabled={{enable_services}}
  tags:
      - enable_services
      - enable_user-preferences

- name: enable user-sessions service
  sudo: yes
  service: name={{user_sessions.service_name}} enabled={{enable_services}}
  tags:
      - enable_services
      - enable_user-sessions

- name: enable tree-urls service
  sudo: yes
  service: name={{tree_urls.service_name}} enabled={{enable_services}}
  tags:
      - enable_services
      - enable_tree-urls

- name: enable notificationagent service
  sudo: yes
  service: name={{notificationagent.service_name}} enabled={{enable_services}}
  tags:
      - enable_services
      - enable_notification-agent

- name: enable metadactyl service
  sudo: yes
  service: name={{metadactyl.service_name}} enabled={{enable_services}}
  tags:
      - enable_services
      - enable_metadactyl

- name: enable kifshare service
  sudo: yes
  service: name={{kifshare.service_name}} enabled={{enable_services}}
  tags:
      - enable_services
      - enable_kifshare

- name: enable jex-events service
  sudo: yes
  service: name={{jexevents.service_name}} enabled={{enable_services}}
  tags:
      - enable_services
      - enable_jex-events

- name: enable iplant-email service
  sudo: yes
  service: name={{iplant_email.service_name}} enabled={{enable_services}}
  tags:
      - enable_services
      - enable_iplant-email

- name: enable iplant-groups service
  sudo: yes
  service: name={{iplant_groups.service_name}} enabled={{enable_services}}
  tags:
      - enable_services
      - enable_iplant-groups

- name: enable donkey service
  sudo: yes
  service: name={{donkey.service_name}} enabled={{enable_services}}
  tags:
      - enable_services
      - enable_donkey

- name: enable data-info service
  sudo: yes
  service: name={{data_info.service_name}} enabled={{enable_services}}
  tags:
      - enable_services
      - enable_data-info

- name: enable metadata service
  sudo: yes
  service: name={{metadata.service_name}} enabled={{enable_services}}
  tags:
      - enable_services
      - enable_metadata

- name: enable condor-log-monitor service
  sudo: yes
  service: name={{condor_log_monitor.service_name}} enabled={{enable_services}}
  tags:
      - enable_services
      - enable_condor-log-monitor

- name: enable clockwork service
  sudo: yes
  service: name={{clockwork.service_name}} enabled={{enable_services}}
  tags:
      - enable_services
      - enable_clockwork

###################################
# Enable/disable parasitic services
###################################
- name: enable monkey service
  sudo: yes
  service: name={{monkey.service_name}} enabled={{enable_services}}
  when: (not parasitic)
  tags:
      - enable_services
      - enable_monkey

- name: enable infosquito service
  sudo: yes
  service: name={{infosquito.service_name}} enabled={{enable_services}}
  when: (not parasitic)
  tags:
      - enable_services
      - enable_infosquito

- name: enable info-typer service
  sudo: yes
  service: name={{info_typer.service_name}} enabled={{enable_services}}
  when: (not parasitic)
  tags:
      - enable_services
      - enable_info-typer

- name: enable dewey service
  sudo: yes
  service: name={{dewey.service_name}} enabled={{enable_services}}
  when: (not parasitic)
  tags:
      - enable_services
      - enable_dewey
