node('secondary') {
    stage 'Checkout'
    git url: 'https://github.com/cyverse/DE.git', branch: 'dev'

    stage 'Test'
    dir('golang') {
        sh 'docker pull discoenv/buildenv'
        sh 'docker run --rm -v $(pwd):/build -w /build discoenv/buildenv gb vendor restore'
        sh 'docker run --rm -v $(pwd):/build -w /build discoenv/buildenv gb test'
    }

    stage 'Build'
    dir('golang') {
        sh 'docker run --rm -v $(pwd):/build -w /build discoenv/buildenv gb build'
        sh 'docker run --rm -v $(pwd):/build -w /build discoenv/buildenv chmod -R a+rwx /build'
    }

    stash includes: '*', name: 'go_checkout'
}

node('tertiary') {
    stage 'Docker Build'
    unstash 'go_checkout'
    dir('golang') {
        sh 'docker build -f jobservices.docker --rm -t discoenv/jobservices:dev .'
    }

    stage 'Docker Push'
    dir ('golang') {
        sh 'ls -l bin/'
    }
    stash includes: '*', name: 'go_checkout'
}

node ('secondary') {
  stage 'Deployment'
  unstash 'go_checkout'
  sh 'ls -l golang/bin/'
}
