package org.iplantc.de.client.models.errors.diskResources;

public enum DiskResourceErrorCode {

    ERR_DOES_NOT_EXIST("ERR_DOES_NOT_EXIST"), 
    ERR_EXISTS("ERR_EXISTS"), 
    ERR_NOT_WRITEABLE("ERR_NOT_WRITEABLE"), 
    ERR_NOT_READABLE("ERR_NOT_READABLE"), 
    ERR_WRITEABLE("ERR_WRITEABLE"), 
    ERR_READABLE("ERR_READABLE"), 
    ERR_NOT_A_USER("ERR_NOT_A_USER"), 
    ERR_NOT_A_FILE("ERR_NOT_A_FILE"), 
    ERR_NOT_A_FOLDER("ERR_NOT_A_FOLDER"), 
    ERR_IS_A_FILE("ERR_IS_A_FILE"), 
    ERR_IS_A_FOLDER("ERR_IS_A_FOLDER"), 
    ERR_INVALID_JSON("ERR_INVALID_JSON"),
    ERR_BAD_OR_MISSING_FIELD("ERR_BAD_OR_MISSING_FIELD"), 
    ERR_MISSING_FORM_FIELD("ERR_MISSING_FORM_FIELD"), 
    ERR_NOT_AUTHORIZED("ERR_NOT_AUTHORIZED"), 
    ERR_MISSING_QUERY_PARAMETER("ERR_MISSING_QUERY_PARAMETER"), 
    ERR_INCOMPLETE_DELETION("ERR_INCOMPLETE_DELETION"), 
    ERR_INCOMPLETE_MOVE("ERR_INCOMPLETE_MOVE"), 
    ERR_INCOMPLETE_RENAME("ERR_INCOMPLETE_RENAME"), 
    ERR_REQUEST_FAILED("ERR_REQUEST_FAILED"), 
    ERR_UNCHECKED_EXCEPTION("ERR_UNCHECKED_EXCEPTION"), 
    ERR_NOT_OWNER("ERR_NOT_OWNER"), 
    ERR_INVALID_COPY("ERR_INVALID_COPY"),
    ERR_TOO_MANY_PATHS("ERR_TOO_MANY_PATHS");

    private String errMsg;

    private DiskResourceErrorCode(String errMsg) {
        this.errMsg = errMsg;
    }

    @Override
    public String toString() {
        return errMsg;
    }
}
