package resource_types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/middleware"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewDeleteResourceTypesIDParams creates a new DeleteResourceTypesIDParams object
// with the default values initialized.
func NewDeleteResourceTypesIDParams() DeleteResourceTypesIDParams {
	var ()
	return DeleteResourceTypesIDParams{}
}

// DeleteResourceTypesIDParams contains all the bound params for the delete resource types ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteResourceTypesID
type DeleteResourceTypesIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The resource type ID.
	  Required: true
	  In: path
	*/
	ID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *DeleteResourceTypesIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rID, rhkID, _ := route.Params.GetOK("id")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteResourceTypesIDParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.ID = raw

	return nil
}
