package resource_types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"permissions/models"
)

/*DeleteResourceTypeByNameOK Deleted

swagger:response deleteResourceTypeByNameOK
*/
type DeleteResourceTypeByNameOK struct {
}

// NewDeleteResourceTypeByNameOK creates DeleteResourceTypeByNameOK with default headers values
func NewDeleteResourceTypeByNameOK() *DeleteResourceTypeByNameOK {
	return &DeleteResourceTypeByNameOK{}
}

// WriteResponse to the client
func (o *DeleteResourceTypeByNameOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
}

/*DeleteResourceTypeByNameBadRequest Bad Request

swagger:response deleteResourceTypeByNameBadRequest
*/
type DeleteResourceTypeByNameBadRequest struct {

	// In: body
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewDeleteResourceTypeByNameBadRequest creates DeleteResourceTypeByNameBadRequest with default headers values
func NewDeleteResourceTypeByNameBadRequest() *DeleteResourceTypeByNameBadRequest {
	return &DeleteResourceTypeByNameBadRequest{}
}

// WithPayload adds the payload to the delete resource type by name bad request response
func (o *DeleteResourceTypeByNameBadRequest) WithPayload(payload *models.ErrorOut) *DeleteResourceTypeByNameBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resource type by name bad request response
func (o *DeleteResourceTypeByNameBadRequest) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResourceTypeByNameBadRequest) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteResourceTypeByNameNotFound Not Found

swagger:response deleteResourceTypeByNameNotFound
*/
type DeleteResourceTypeByNameNotFound struct {

	// In: body
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewDeleteResourceTypeByNameNotFound creates DeleteResourceTypeByNameNotFound with default headers values
func NewDeleteResourceTypeByNameNotFound() *DeleteResourceTypeByNameNotFound {
	return &DeleteResourceTypeByNameNotFound{}
}

// WithPayload adds the payload to the delete resource type by name not found response
func (o *DeleteResourceTypeByNameNotFound) WithPayload(payload *models.ErrorOut) *DeleteResourceTypeByNameNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resource type by name not found response
func (o *DeleteResourceTypeByNameNotFound) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResourceTypeByNameNotFound) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteResourceTypeByNameInternalServerError delete resource type by name internal server error

swagger:response deleteResourceTypeByNameInternalServerError
*/
type DeleteResourceTypeByNameInternalServerError struct {

	// In: body
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewDeleteResourceTypeByNameInternalServerError creates DeleteResourceTypeByNameInternalServerError with default headers values
func NewDeleteResourceTypeByNameInternalServerError() *DeleteResourceTypeByNameInternalServerError {
	return &DeleteResourceTypeByNameInternalServerError{}
}

// WithPayload adds the payload to the delete resource type by name internal server error response
func (o *DeleteResourceTypeByNameInternalServerError) WithPayload(payload *models.ErrorOut) *DeleteResourceTypeByNameInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resource type by name internal server error response
func (o *DeleteResourceTypeByNameInternalServerError) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResourceTypeByNameInternalServerError) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
