package resource_types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/httpkit/middleware"
	"github.com/go-swagger/go-swagger/httpkit/validate"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewDeleteResourceTypeByNameParams creates a new DeleteResourceTypeByNameParams object
// with the default values initialized.
func NewDeleteResourceTypeByNameParams() DeleteResourceTypeByNameParams {
	var ()
	return DeleteResourceTypeByNameParams{}
}

// DeleteResourceTypeByNameParams contains all the bound params for the delete resource type by name operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteResourceTypeByName
type DeleteResourceTypeByNameParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The resource type name to search for.
	  Required: true
	  In: query
	*/
	ResourceTypeName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *DeleteResourceTypeByNameParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := httpkit.Values(r.URL.Query())

	qResourceTypeName, qhkResourceTypeName, _ := qs.GetOK("resource_type_name")
	if err := o.bindResourceTypeName(qResourceTypeName, qhkResourceTypeName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteResourceTypeByNameParams) bindResourceTypeName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("resource_type_name", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("resource_type_name", "query", raw); err != nil {
		return err
	}

	o.ResourceTypeName = raw

	return nil
}
