package resource_types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"permissions/models"
)

/*GetResourceTypesOK Success

swagger:response getResourceTypesOK
*/
type GetResourceTypesOK struct {

	// In: body
	Payload *models.ResourceTypesOut `json:"body,omitempty"`
}

// NewGetResourceTypesOK creates GetResourceTypesOK with default headers values
func NewGetResourceTypesOK() *GetResourceTypesOK {
	return &GetResourceTypesOK{}
}

// WithPayload adds the payload to the get resource types o k response
func (o *GetResourceTypesOK) WithPayload(payload *models.ResourceTypesOut) *GetResourceTypesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get resource types o k response
func (o *GetResourceTypesOK) SetPayload(payload *models.ResourceTypesOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResourceTypesOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetResourceTypesInternalServerError get resource types internal server error

swagger:response getResourceTypesInternalServerError
*/
type GetResourceTypesInternalServerError struct {

	// In: body
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewGetResourceTypesInternalServerError creates GetResourceTypesInternalServerError with default headers values
func NewGetResourceTypesInternalServerError() *GetResourceTypesInternalServerError {
	return &GetResourceTypesInternalServerError{}
}

// WithPayload adds the payload to the get resource types internal server error response
func (o *GetResourceTypesInternalServerError) WithPayload(payload *models.ErrorOut) *GetResourceTypesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get resource types internal server error response
func (o *GetResourceTypesInternalServerError) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResourceTypesInternalServerError) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
