package resource_types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-swagger/go-swagger/httpkit/middleware"
)

// PostResourceTypesIDHandlerFunc turns a function with the right signature into a post resource types ID handler
type PostResourceTypesIDHandlerFunc func(PostResourceTypesIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostResourceTypesIDHandlerFunc) Handle(params PostResourceTypesIDParams) middleware.Responder {
	return fn(params)
}

// PostResourceTypesIDHandler interface for that can handle valid post resource types ID params
type PostResourceTypesIDHandler interface {
	Handle(PostResourceTypesIDParams) middleware.Responder
}

// NewPostResourceTypesID creates a new http.Handler for the post resource types ID operation
func NewPostResourceTypesID(ctx *middleware.Context, handler PostResourceTypesIDHandler) *PostResourceTypesID {
	return &PostResourceTypesID{Context: ctx, Handler: handler}
}

/*PostResourceTypesID swagger:route POST /resource_types/{id} resource_types postResourceTypesId

Update a Resource Type

Updates the name or description of a resource type. The new name of the resource type must be unique if one is provided.

*/
type PostResourceTypesID struct {
	Context *middleware.Context
	Handler PostResourceTypesIDHandler
}

func (o *PostResourceTypesID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPostResourceTypesIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
