package resource_types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"permissions/models"
)

/*PostResourceTypesCreated Created

swagger:response postResourceTypesCreated
*/
type PostResourceTypesCreated struct {

	// In: body
	Payload *models.ResourceTypeOut `json:"body,omitempty"`
}

// NewPostResourceTypesCreated creates PostResourceTypesCreated with default headers values
func NewPostResourceTypesCreated() *PostResourceTypesCreated {
	return &PostResourceTypesCreated{}
}

// WithPayload adds the payload to the post resource types created response
func (o *PostResourceTypesCreated) WithPayload(payload *models.ResourceTypeOut) *PostResourceTypesCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post resource types created response
func (o *PostResourceTypesCreated) SetPayload(payload *models.ResourceTypeOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostResourceTypesCreated) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostResourceTypesBadRequest Bad Request

swagger:response postResourceTypesBadRequest
*/
type PostResourceTypesBadRequest struct {

	// In: body
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewPostResourceTypesBadRequest creates PostResourceTypesBadRequest with default headers values
func NewPostResourceTypesBadRequest() *PostResourceTypesBadRequest {
	return &PostResourceTypesBadRequest{}
}

// WithPayload adds the payload to the post resource types bad request response
func (o *PostResourceTypesBadRequest) WithPayload(payload *models.ErrorOut) *PostResourceTypesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post resource types bad request response
func (o *PostResourceTypesBadRequest) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostResourceTypesBadRequest) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostResourceTypesInternalServerError post resource types internal server error

swagger:response postResourceTypesInternalServerError
*/
type PostResourceTypesInternalServerError struct {

	// In: body
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewPostResourceTypesInternalServerError creates PostResourceTypesInternalServerError with default headers values
func NewPostResourceTypesInternalServerError() *PostResourceTypesInternalServerError {
	return &PostResourceTypesInternalServerError{}
}

// WithPayload adds the payload to the post resource types internal server error response
func (o *PostResourceTypesInternalServerError) WithPayload(payload *models.ErrorOut) *PostResourceTypesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post resource types internal server error response
func (o *PostResourceTypesInternalServerError) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostResourceTypesInternalServerError) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
