package resource_types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/httpkit/middleware"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"permissions/models"
)

// NewPostResourceTypesIDParams creates a new PostResourceTypesIDParams object
// with the default values initialized.
func NewPostResourceTypesIDParams() PostResourceTypesIDParams {
	var ()
	return PostResourceTypesIDParams{}
}

// PostResourceTypesIDParams contains all the bound params for the post resource types ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostResourceTypesID
type PostResourceTypesIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The resource type ID.
	  Required: true
	  In: path
	*/
	ID string
	/*The new name and description of the resource type.
	  Required: true
	  In: body
	*/
	ResourceTypeIn *models.ResourceTypeIn
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *PostResourceTypesIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rID, rhkID, _ := route.Params.GetOK("id")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	if httpkit.HasBody(r) {
		defer r.Body.Close()
		var body models.ResourceTypeIn
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("resourceTypeIn", "body"))
			} else {
				res = append(res, errors.NewParseError("resourceTypeIn", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.ResourceTypeIn = &body
			}
		}

	} else {
		res = append(res, errors.Required("resourceTypeIn", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostResourceTypesIDParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.ID = raw

	return nil
}
