package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-swagger/go-swagger/httpkit/middleware"
)

// GetHandlerFunc turns a function with the right signature into a get handler
type GetHandlerFunc func() middleware.Responder

// Handle executing the request and returning a response
func (fn GetHandlerFunc) Handle() middleware.Responder {
	return fn()
}

// GetHandler interface for that can handle valid get params
type GetHandler interface {
	Handle() middleware.Responder
}

// NewGet creates a new http.Handler for the get operation
func NewGet(ctx *middleware.Context, handler GetHandler) *Get {
	return &Get{Context: ctx, Handler: handler}
}

/*Get swagger:route GET / status get

Service Status Information

Displays general information about the service and can be used to determine whether or not the service is running.

*/
type Get struct {
	Context *middleware.Context
	Handler GetHandler
}

func (o *Get) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)

	if err := o.Context.BindValidRequest(r, route, nil); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle() // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
