---
- name: update docker-py
  pip: name="docker-py" state="latest"

- name: pull the app registration docker image
  docker_image: name="{{ app_registration_repo }}" tag="{{ docker_tag }}"

- name: pull the configuration docker image
  docker_image: name="{{ config_repo }}" tag="{{ docker_tag }}"

- name: delete the configuration container if it exists
  docker_container: name="app-registration-configs" state="absent"

- name: create the configuration container
  docker_container:
    name: "app-registration-configs"
    image: "{{ config_repo }}:{{ docker_tag }}"
    state: "present"

- name: register existing DE apps
  docker_container:
    name: "app-registration"
    image: "{{ app_registration_repo }}:{{ docker_tag }}"
    volumes_from:
      - "app-registration-configs"
    command: "--config={{ config_path }} --de-database-name={{ de_database_name }}"

- name: remove the app registration container
  docker_container: name="app-registration" state="absent"

- name: remove the app registration config container
  docker_container: name="app-registration-configs" state="absent"
