package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*ErrorOut error out

swagger:model error_out
*/
type ErrorOut struct {

	/* reason

	Required: true
	Min Length: 1
	*/
	Reason *string `json:"reason"`
}

// Validate validates this error out
func (m *ErrorOut) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReason(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ErrorOut) validateReason(formats strfmt.Registry) error {

	if err := validate.Required("reason", "body", m.Reason); err != nil {
		return err
	}

	if err := validate.MinLength("reason", "body", string(*m.Reason), 1); err != nil {
		return err
	}

	return nil
}
