package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
)

/*PermissionGrantRequest Information for granting permission to a user.

swagger:model permission_grant_request
*/
type PermissionGrantRequest struct {

	/* permission level

	Required: true
	*/
	PermissionLevel PermissionLevel `json:"permission_level"`

	/* resource

	Required: true
	*/
	Resource *ResourceIn `json:"resource"`

	/* subject

	Required: true
	*/
	Subject *SubjectIn `json:"subject"`
}

// Validate validates this permission grant request
func (m *PermissionGrantRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePermissionLevel(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateResource(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateSubject(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PermissionGrantRequest) validatePermissionLevel(formats strfmt.Registry) error {

	if err := m.PermissionLevel.Validate(formats); err != nil {
		return err
	}

	return nil
}

func (m *PermissionGrantRequest) validateResource(formats strfmt.Registry) error {

	if m.Resource != nil {

		if err := m.Resource.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}

func (m *PermissionGrantRequest) validateSubject(formats strfmt.Registry) error {

	if m.Subject != nil {

		if err := m.Subject.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
