package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
)

/*PermissionPutRequest Specifies the permission level to assign.

swagger:model permission_put_request
*/
type PermissionPutRequest struct {

	/* permission level

	Required: true
	*/
	PermissionLevel PermissionLevel `json:"permission_level"`
}

// Validate validates this permission put request
func (m *PermissionPutRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePermissionLevel(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PermissionPutRequest) validatePermissionLevel(formats strfmt.Registry) error {

	if err := m.PermissionLevel.Validate(formats); err != nil {
		return err
	}

	return nil
}
