package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*ResourceTypeIn An incoming resource type.

swagger:model resource_type_in
*/
type ResourceTypeIn struct {

	/* A brief description of the resource type.
	 */
	Description string `json:"description,omitempty"`

	/* The name of the resource type.

	Required: true
	Min Length: 1
	*/
	Name *string `json:"name"`
}

// Validate validates this resource type in
func (m *ResourceTypeIn) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResourceTypeIn) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", string(*m.Name), 1); err != nil {
		return err
	}

	return nil
}
