package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*ResourcesOut A list of resources.

swagger:model resources_out
*/
type ResourcesOut struct {

	/* The list of resources.

	Required: true
	*/
	Resources []*ResourceOut `json:"resources"`
}

// Validate validates this resources out
func (m *ResourcesOut) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResources(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResourcesOut) validateResources(formats strfmt.Registry) error {

	if err := validate.Required("resources", "body", m.Resources); err != nil {
		return err
	}

	for i := 0; i < len(m.Resources); i++ {

		if err := m.Resources[i].Validate(formats); err != nil {
			return err
		}

	}

	return nil
}
