package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*ResourceTypesOut resource types out

swagger:model resource_types_out
*/
type ResourceTypesOut struct {

	/* resource types

	Required: true
	*/
	ResourceTypes []*ResourceTypeOut `json:"resource_types"`
}

// Validate validates this resource types out
func (m *ResourceTypesOut) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResourceTypes(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResourceTypesOut) validateResourceTypes(formats strfmt.Registry) error {

	if err := validate.Required("resource_types", "body", m.ResourceTypes); err != nil {
		return err
	}

	for i := 0; i < len(m.ResourceTypes); i++ {

		if err := m.ResourceTypes[i].Validate(formats); err != nil {
			return err
		}

	}

	return nil
}
