package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*SubjectType The subject type.

swagger:model subject_type
*/
type SubjectType string

// for schema
var subjectTypeEnum []interface{}

func (m SubjectType) validateSubjectTypeEnum(path, location string, value SubjectType) error {
	if subjectTypeEnum == nil {
		var res []SubjectType
		if err := json.Unmarshal([]byte(`["user","group"]`), &res); err != nil {
			return err
		}
		for _, v := range res {
			subjectTypeEnum = append(subjectTypeEnum, v)
		}
	}
	if err := validate.Enum(path, location, value, subjectTypeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this subject type
func (m SubjectType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateSubjectTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
