package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*SubjectsOut A list of subjects.

swagger:model subjects_out
*/
type SubjectsOut struct {

	/* The list of subjects.

	Required: true
	*/
	Subjects []*SubjectOut `json:"subjects"`
}

// Validate validates this subjects out
func (m *SubjectsOut) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSubjects(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SubjectsOut) validateSubjects(formats strfmt.Registry) error {

	if err := validate.Required("subjects", "body", m.Subjects); err != nil {
		return err
	}

	for i := 0; i < len(m.Subjects); i++ {

		if err := m.Subjects[i].Validate(formats); err != nil {
			return err
		}

	}

	return nil
}
