---
# tasks file for elk-logstash

- name: pull elk logstash image
  shell: docker pull {{docker.user}}/{{ elk.logstash.image_name }}
  register: docker_pull_v
  changed_when: docker_pull_v.stdout.find('Image is up to date') == -1
  tags:
      - docker_pull
      - docker_pull_logstash

- name: place Systemd service files
  template: src={{ elk.logstash.service_name }} dest=/usr/lib/systemd/system group=root owner=root mode=0664
  register: service_file_v
  tags:
      - update_service_files
      - update_service_files_logstash

- include: place-logstash-configs.yaml        

- name: Reload systemd
  shell: systemctl daemon-reload  
  when: service_file_v.changed 
  tags:
      - update_service_files
      - update_service_files_logstash

- name: enable logstash service
  service: name={{elk.logstash.service_name}} enabled={{enable_services}}
  when: service_file_v.changed 
  tags:
      - enable_services
      - enable_logstash
        
# Always restart logstash        
- name: restart logstash service
  service: name={{elk.logstash.service_name}} state=restarted
  tags:
      - restart_services
      - restart_logstash

