---
dependencies:
    - role: util-cfg-docker-pull-configs
      service_name: "{{anon_files.compose_service}}"
      service_name_short: "{{anon_files.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{anon_files.compose_service}}"
      service_name_short: "{{anon_files.service_name_short}}"

    - role: util-cfg-docker-pull-configs
      service_name: "{{apps.compose_service}}"
      service_name_short: "{{apps.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{apps.compose_service}}"
      service_name_short: "{{apps.service_name_short}}"

    - role: util-cfg-docker-pull-configs
      service_name: "{{clockwork.compose_service}}"
      service_name_short: "{{clockwork.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{clockwork.compose_service}}"
      service_name_short: "{{clockwork.service_name_short}}"

    - role: util-cfg-docker-pull-configs
      service_name: "{{condor_log_monitor.compose_service}}"
      service_name_short: "{{condor_log_monitor.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{condor_log_monitor.compose_service}}"
      service_name_short: "{{condor_log_monitor.service_name_short}}"

    - role: util-cfg-docker-pull-configs
      service_name: "{{data_info.compose_service}}"
      service_name_short: "{{data_info.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{data_info.compose_service}}"
      service_name_short: "{{data_info.service_name_short}}"

    - role: util-cfg-docker-pull-configs
      service_name: "{{dewey.compose_service}}"
      service_name_short: "{{dewey.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{dewey.compose_service}}"
      service_name_short: "{{dewey.service_name_short}}"

    - role: util-cfg-docker-pull-configs
      service_name: "{{exim.compose_service}}"
      service_name_short: "{{exim.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{exim.compose_service}}"
      service_name_short: "{{exim.service_name_short}}"

    - role: util-cfg-docker-pull-configs
      service_name: "{{info_typer.compose_service}}"
      service_name_short: "{{info_typer.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{info_typer.compose_service}}"
      service_name_short: "{{info_typer.service_name_short}}"

    - role: util-cfg-docker-pull-configs
      service_name: "{{infosquito.compose_service}}"
      service_name_short: "{{infosquito.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{infosquito.compose_service}}"
      service_name_short: "{{infosquito.service_name_short}}"

    - role: util-cfg-docker-pull-configs
      service_name: "{{iplant_email.compose_service}}"
      service_name_short: "{{iplant_email.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{iplant_email.compose_service}}"
      service_name_short: "{{iplant_email.service_name_short}}"

    - role: util-cfg-docker-pull-configs
      service_name: "{{iplant_groups.compose_service}}"
      service_name_short: "{{iplant_groups.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{iplant_groups.compose_service}}"
      service_name_short: "{{iplant_groups.service_name_short}}"

    - role: util-cfg-docker-pull-configs
      service_name: "{{jexevents.compose_service}}"
      service_name_short: "{{jexevents.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{jexevents.compose_service}}"
      service_name_short: "{{jexevents.service_name_short}}"

    - role: util-cfg-docker-pull-configs
      service_name: "{{kifshare.compose_service}}"
      service_name_short: "{{kifshare.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{kifshare.compose_service}}"
      service_name_short: "{{kifshare.service_name_short}}"

    - role: util-cfg-docker-pull-configs
      service_name: "{{metadata.compose_service}}"
      service_name_short: "{{metadata.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{metadata.compose_service}}"
      service_name_short: "{{metadata.service_name_short}}"

    - role: util-cfg-docker-pull-configs
      service_name: "{{monkey.compose_service}}"
      service_name_short: "{{monkey.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{monkey.compose_service}}"
      service_name_short: "{{monkey.service_name_short}}"

    - role: util-cfg-docker-pull-configs
      service_name: "{{notificationagent.compose_service}}"
      service_name_short: "{{notificationagent.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{notificationagent.compose_service}}"
      service_name_short: "{{notificationagent.service_name_short}}"

    - role: util-cfg-docker-pull-configs
      service_name: "{{saved_searches.compose_service}}"
      service_name_short: "{{saved_searches.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{saved_searches.compose_service}}"
      service_name_short: "{{saved_searches.service_name_short}}"

    - role: util-cfg-docker-pull-configs
      service_name: "{{templeton_periodic.compose_service}}"
      service_name_short: "{{templeton_periodic.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{templeton_periodic.compose_service}}"
      service_name_short: "{{templeton_periodic.service_name_short}}"

    - role: util-cfg-docker-pull-configs
      service_name: "{{templeton_incremental.compose_service}}"
      service_name_short: "{{templeton_incremental.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{templeton_incremental.compose_service}}"
      service_name_short: "{{templeton_incremental.service_name_short}}"

    - role: util-cfg-docker-pull-configs
      service_name: "{{terrain.compose_service}}"
      service_name_short: "{{terrain.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{terrain.compose_service}}"
      service_name_short: "{{terrain.service_name_short}}"

    - role: util-cfg-docker-pull-configs
      service_name: "{{tree_urls.compose_service}}"
      service_name_short: "{{tree_urls.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{tree_urls.compose_service}}"
      service_name_short: "{{tree_urls.service_name_short}}"

    - role: util-cfg-docker-pull-configs
      service_name: "{{user_preferences.compose_service}}"
      service_name_short: "{{user_preferences.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{user_preferences.compose_service}}"
      service_name_short: "{{user_preferences.service_name_short}}"

    - role: util-cfg-docker-pull-configs
      service_name: "{{user_sessions.compose_service}}"
      service_name_short: "{{user_sessions.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{user_sessions.compose_service}}"
      service_name_short: "{{user_sessions.service_name_short}}"
