package permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"permissions/models"
)

/*GrantPermissionOK Created

swagger:response grantPermissionOK
*/
type GrantPermissionOK struct {

	// In: body
	Payload *models.Permission `json:"body,omitempty"`
}

// NewGrantPermissionOK creates GrantPermissionOK with default headers values
func NewGrantPermissionOK() *GrantPermissionOK {
	return &GrantPermissionOK{}
}

// WithPayload adds the payload to the grant permission o k response
func (o *GrantPermissionOK) WithPayload(payload *models.Permission) *GrantPermissionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the grant permission o k response
func (o *GrantPermissionOK) SetPayload(payload *models.Permission) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GrantPermissionOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GrantPermissionBadRequest Bad Request

swagger:response grantPermissionBadRequest
*/
type GrantPermissionBadRequest struct {

	// In: body
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewGrantPermissionBadRequest creates GrantPermissionBadRequest with default headers values
func NewGrantPermissionBadRequest() *GrantPermissionBadRequest {
	return &GrantPermissionBadRequest{}
}

// WithPayload adds the payload to the grant permission bad request response
func (o *GrantPermissionBadRequest) WithPayload(payload *models.ErrorOut) *GrantPermissionBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the grant permission bad request response
func (o *GrantPermissionBadRequest) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GrantPermissionBadRequest) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GrantPermissionInternalServerError grant permission internal server error

swagger:response grantPermissionInternalServerError
*/
type GrantPermissionInternalServerError struct {

	// In: body
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewGrantPermissionInternalServerError creates GrantPermissionInternalServerError with default headers values
func NewGrantPermissionInternalServerError() *GrantPermissionInternalServerError {
	return &GrantPermissionInternalServerError{}
}

// WithPayload adds the payload to the grant permission internal server error response
func (o *GrantPermissionInternalServerError) WithPayload(payload *models.ErrorOut) *GrantPermissionInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the grant permission internal server error response
func (o *GrantPermissionInternalServerError) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GrantPermissionInternalServerError) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
