package permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"permissions/models"
)

/*ListPermissionsOK OK

swagger:response listPermissionsOK
*/
type ListPermissionsOK struct {

	// In: body
	Payload *models.PermissionList `json:"body,omitempty"`
}

// NewListPermissionsOK creates ListPermissionsOK with default headers values
func NewListPermissionsOK() *ListPermissionsOK {
	return &ListPermissionsOK{}
}

// WithPayload adds the payload to the list permissions o k response
func (o *ListPermissionsOK) WithPayload(payload *models.PermissionList) *ListPermissionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list permissions o k response
func (o *ListPermissionsOK) SetPayload(payload *models.PermissionList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListPermissionsOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ListPermissionsInternalServerError list permissions internal server error

swagger:response listPermissionsInternalServerError
*/
type ListPermissionsInternalServerError struct {

	// In: body
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewListPermissionsInternalServerError creates ListPermissionsInternalServerError with default headers values
func NewListPermissionsInternalServerError() *ListPermissionsInternalServerError {
	return &ListPermissionsInternalServerError{}
}

// WithPayload adds the payload to the list permissions internal server error response
func (o *ListPermissionsInternalServerError) WithPayload(payload *models.ErrorOut) *ListPermissionsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list permissions internal server error response
func (o *ListPermissionsInternalServerError) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListPermissionsInternalServerError) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
