Dear $name$,

Your app, $app_name$, has been administratively deprecated in the Discovery Environment.
Usually this happens when a newer version of this app is made publicly available in the Discovery Environment.
This app is still viewable by its direct link, though it can no longer be searched or used within the Discovery Environment:
$app_link$

If you believe this app should not have been deprecated, please contact support@cyverse.org.

Thank you,
The CyVerse Team
