def common
node('secondary') {
    stage 'Checkout'
    common = load 'jenkins/common.groovy'

    stage 'Test'
    dir('golang') {
        sh 'docker pull discoenv/buildenv'
        common.buildenv('gb vendor restore')
        common.buildenv('gb test')
    }

    stage 'Build'
    dir('golang') {
        common.buildenv("gb build -f -F --ldflags \"-X main.appver=${common.version()} -X main.gitref=${common.gitcommit()} -X main.builtby=${common.user()}\"")
        common.buildenv('chmod -R a+rwx /build')
    }
    stash includes: 'golang/**', name: 'golang'
}

node('secondary') {
    stage 'Docker Build'
    unstash 'golang'

    dir('golang') {
        common.dockerbuild('jobservices.docker', 'discoenv/jobservices:dev')
    }

    stage 'Docker Push'
    common.dockerpush('discoenv/jobservices:dev')
}

node('secondary') {
    stage 'Deployment'
    sh 'ls -l golang/bin/'
}
