---
- name: place Systemd service files
  sudo: yes
  template: src={{jex.service_name}} dest=/usr/lib/systemd/system/ group=root owner=root mode=0664
  tags:
      - update_service_files
      - update_service_file_jex

- name: reload daemon
  sudo: yes
  shell: systemctl daemon-reload
  tags:
      - update_service_files
      - update_service_file_jex

- name: start jex
  sudo: yes
  service: name={{jex.service_name}} state=restarted
  tags:
    - jex
    - restart_services
    - restart_jex

- name: enable jex
  sudo: yes
  service: name={{jex.service_name}} enabled={{enable_services}}
  tags:
      - enable_services
      - enable_jex
