package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"permissions/models"
)

/*DeleteResourceByNameOK OK

swagger:response deleteResourceByNameOK
*/
type DeleteResourceByNameOK struct {
}

// NewDeleteResourceByNameOK creates DeleteResourceByNameOK with default headers values
func NewDeleteResourceByNameOK() *DeleteResourceByNameOK {
	return &DeleteResourceByNameOK{}
}

// WriteResponse to the client
func (o *DeleteResourceByNameOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
}

/*DeleteResourceByNameNotFound Not Found

swagger:response deleteResourceByNameNotFound
*/
type DeleteResourceByNameNotFound struct {

	// In: body
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewDeleteResourceByNameNotFound creates DeleteResourceByNameNotFound with default headers values
func NewDeleteResourceByNameNotFound() *DeleteResourceByNameNotFound {
	return &DeleteResourceByNameNotFound{}
}

// WithPayload adds the payload to the delete resource by name not found response
func (o *DeleteResourceByNameNotFound) WithPayload(payload *models.ErrorOut) *DeleteResourceByNameNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resource by name not found response
func (o *DeleteResourceByNameNotFound) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResourceByNameNotFound) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteResourceByNameInternalServerError delete resource by name internal server error

swagger:response deleteResourceByNameInternalServerError
*/
type DeleteResourceByNameInternalServerError struct {

	// In: body
	Payload *models.ErrorOut `json:"body,omitempty"`
}

// NewDeleteResourceByNameInternalServerError creates DeleteResourceByNameInternalServerError with default headers values
func NewDeleteResourceByNameInternalServerError() *DeleteResourceByNameInternalServerError {
	return &DeleteResourceByNameInternalServerError{}
}

// WithPayload adds the payload to the delete resource by name internal server error response
func (o *DeleteResourceByNameInternalServerError) WithPayload(payload *models.ErrorOut) *DeleteResourceByNameInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resource by name internal server error response
func (o *DeleteResourceByNameInternalServerError) SetPayload(payload *models.ErrorOut) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResourceByNameInternalServerError) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
