package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/httpkit/middleware"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewListResourcesParams creates a new ListResourcesParams object
// with the default values initialized.
func NewListResourcesParams() ListResourcesParams {
	var ()
	return ListResourcesParams{}
}

// ListResourcesParams contains all the bound params for the list resources operation
// typically these are obtained from a http.Request
//
// swagger:parameters listResources
type ListResourcesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The resource name to search for.
	  In: query
	*/
	ResourceName *string
	/*The resource type name to search for.
	  In: query
	*/
	ResourceTypeName *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *ListResourcesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := httpkit.Values(r.URL.Query())

	qResourceName, qhkResourceName, _ := qs.GetOK("resource_name")
	if err := o.bindResourceName(qResourceName, qhkResourceName, route.Formats); err != nil {
		res = append(res, err)
	}

	qResourceTypeName, qhkResourceTypeName, _ := qs.GetOK("resource_type_name")
	if err := o.bindResourceTypeName(qResourceTypeName, qhkResourceTypeName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ListResourcesParams) bindResourceName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.ResourceName = &raw

	return nil
}

func (o *ListResourcesParams) bindResourceTypeName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.ResourceTypeName = &raw

	return nil
}
