package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-swagger/go-swagger/httpkit/middleware"
)

// UpdateResourceHandlerFunc turns a function with the right signature into a update resource handler
type UpdateResourceHandlerFunc func(UpdateResourceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateResourceHandlerFunc) Handle(params UpdateResourceParams) middleware.Responder {
	return fn(params)
}

// UpdateResourceHandler interface for that can handle valid update resource params
type UpdateResourceHandler interface {
	Handle(UpdateResourceParams) middleware.Responder
}

// NewUpdateResource creates a new http.Handler for the update resource operation
func NewUpdateResource(ctx *middleware.Context, handler UpdateResourceHandler) *UpdateResource {
	return &UpdateResource{Context: ctx, Handler: handler}
}

/*UpdateResource swagger:route PUT /resources/{id} resources updateResource

Update a Resource

Updates a resource in the database.

*/
type UpdateResource struct {
	Context *middleware.Context
	Handler UpdateResourceHandler
}

func (o *UpdateResource) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewUpdateResourceParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
